version: '3.8'

services:
  # 后端服务器
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ADMIN_KEY=admin123
      - CORS_ORIGIN=http://localhost:5173,http://localhost:5174
    volumes:
      - ./server/logs:/app/logs
    restart: unless-stopped
    networks:
      - sky-journey-network

  # 前端客户端
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - sky-journey-network

  # 管理后台
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5174:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - sky-journey-network

  # Nginx 反向代理（可选）
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl/certs
    depends_on:
      - server
      - client
      - admin
    restart: unless-stopped
    networks:
      - sky-journey-network

networks:
  sky-journey-network:
    driver: bridge

volumes:
  server_logs:
    driver: local
